#!/bin/bash
# ============================================================================
# setup-cloudflare-tunnel.sh
# One-time setup for the Bonsai BIM Viewer Cloudflare Tunnel
#
# This creates a named tunnel called "bonsai-viewer" that routes:
#   - viewer.YOURDOMAIN.com  -> localhost:5173  (Vite dev server / viewer)
#   - chat.YOURDOMAIN.com    -> localhost:5174  (chat proxy / AI agent)
#
# Prerequisites:
#   - cloudflared installed (brew install cloudflare/cloudflare/cloudflared)
#   - A domain on Cloudflare (DNS managed by Cloudflare)
#
# Usage:
#   ./scripts/setup-cloudflare-tunnel.sh <yourdomain.com>
#
# Example:
#   ./scripts/setup-cloudflare-tunnel.sh openclaw.dev
#   -> Creates viewer.openclaw.dev and chat.openclaw.dev
# ============================================================================

set -euo pipefail

TUNNEL_NAME="bonsai-viewer"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$HOME/.cloudflared"

# ---------------------------------------------------------------------------
# Validate args
# ---------------------------------------------------------------------------
if [ $# -lt 1 ]; then
  echo "Usage: $0 <your-domain.com>"
  echo ""
  echo "Example: $0 openclaw.dev"
  echo "  This will create:"
  echo "    viewer.openclaw.dev -> localhost:5173 (BIM viewer)"
  echo "    chat.openclaw.dev   -> localhost:5174 (AI chat proxy)"
  exit 1
fi

DOMAIN="$1"
VIEWER_HOST="viewer.${DOMAIN}"
CHAT_HOST="chat.${DOMAIN}"

echo "============================================"
echo "  Bonsai BIM Viewer - Cloudflare Tunnel Setup"
echo "============================================"
echo ""
echo "Domain:  $DOMAIN"
echo "Viewer:  https://$VIEWER_HOST -> localhost:5173"
echo "Chat:    https://$CHAT_HOST   -> localhost:5174"
echo ""

# ---------------------------------------------------------------------------
# Step 1: Authenticate (if not already done)
# ---------------------------------------------------------------------------
if [ ! -f "$CONFIG_DIR/cert.pem" ]; then
  echo "[1/4] Authenticating with Cloudflare..."
  echo "  A browser window will open. Log in and authorize the domain."
  echo ""
  cloudflared tunnel login
  echo ""
  echo "  Authentication complete."
else
  echo "[1/4] Already authenticated with Cloudflare (cert.pem exists)."
fi
echo ""

# ---------------------------------------------------------------------------
# Step 2: Create the named tunnel
# ---------------------------------------------------------------------------
echo "[2/4] Creating named tunnel: $TUNNEL_NAME"

# Check if tunnel already exists
if cloudflared tunnel list 2>/dev/null | grep -q "$TUNNEL_NAME"; then
  echo "  Tunnel '$TUNNEL_NAME' already exists. Skipping creation."
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')
else
  cloudflared tunnel create "$TUNNEL_NAME"
  TUNNEL_ID=$(cloudflared tunnel list 2>/dev/null | grep "$TUNNEL_NAME" | awk '{print $1}')
  echo "  Created tunnel: $TUNNEL_NAME (ID: $TUNNEL_ID)"
fi
echo ""

# ---------------------------------------------------------------------------
# Step 3: Write the tunnel config
# ---------------------------------------------------------------------------
echo "[3/4] Writing tunnel config to $CONFIG_DIR/config.yml"

cat > "$CONFIG_DIR/config.yml" << EOF
# Bonsai BIM Viewer - Cloudflare Tunnel Configuration
# Generated by setup-cloudflare-tunnel.sh on $(date -Iseconds)
#
# Start with: cloudflared tunnel run $TUNNEL_NAME
# Or use:     ./scripts/start-tunnel.sh

tunnel: $TUNNEL_ID
credentials-file: $CONFIG_DIR/${TUNNEL_ID}.json

ingress:
  # BIM Viewer (Vite dev server)
  - hostname: $VIEWER_HOST
    service: http://localhost:5173
    originRequest:
      # Required for SharedArrayBuffer (web-ifc WASM threading)
      httpHostHeader: $VIEWER_HOST

  # Chat / AI Agent Proxy
  - hostname: $CHAT_HOST
    service: http://localhost:5174
    originRequest:
      httpHostHeader: $CHAT_HOST

  # Catch-all (required by cloudflared)
  - service: http_status:404
EOF

echo "  Config written."
echo ""

# ---------------------------------------------------------------------------
# Step 4: Create DNS routes
# ---------------------------------------------------------------------------
echo "[4/4] Creating DNS CNAME records..."

echo "  Routing $VIEWER_HOST -> tunnel $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$VIEWER_HOST" || echo "  (DNS record may already exist)"

echo "  Routing $CHAT_HOST -> tunnel $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$CHAT_HOST" || echo "  (DNS record may already exist)"

echo ""
echo "============================================"
echo "  Setup Complete!"
echo "============================================"
echo ""
echo "To start the tunnel:"
echo "  ./scripts/start-tunnel.sh"
echo ""
echo "Teammates can access:"
echo "  Viewer: https://$VIEWER_HOST"
echo "  Chat:   https://$CHAT_HOST"
echo ""
echo "NEXT STEPS (recommended):"
echo "  1. Set up Cloudflare Access for team authentication."
echo "     See: viewer/TUNNEL-SETUP.md for instructions."
echo "  2. Start the viewer + chat proxy first:"
echo "     ./scripts/serve-bonsai-viewer.sh"
echo "  3. Then start the tunnel in another terminal:"
echo "     ./scripts/start-tunnel.sh"
echo ""
